version: '3.8'
services:
  php-apache-environment:
    container_name: php5.3-apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 3000:80